planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
arm:
  planner_configs:
    - SBLkConfigDefault
  projection_evaluator: joints(joint1,joint2)
  longest_valid_segment_fraction: 0.05
  default_planner_config: SBLkConfigDefault
